# Generated by Django 4.0.5 on 2022-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_app', '0002_remove_post_comments_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_path'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='upload_path'),
        ),
    ]
